version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.3.0"

    steps:
      - checkout
      - run:
          name: Reset simulators with Snapshot
          command: fastlane snapshot reset_simulators --force

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: set -o pipefail && xcodebuild clean build test -project BiometricLocker.xcodeproj -scheme "BiometricLocker" -destination 'platform=iOS Simulator,name=iPhone 8' | xcpretty --color && exit ${PIPESTATUS[0]}

